import time
import random
from time import sleep
import pyautogui
from pyautogui import press

print("loading virus exe")

time.sleep(7)
pyautogui.hotkey("ctrl", "esc")
time.sleep(1)
pyautogui.typewrite("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
time.sleep(1)
pyautogui.press("enter")
time.sleep(5)
pyautogui.press("f5")
time.sleep(5)
pyautogui.hotkey("win", "d")
sleep(1)
pyautogui.rightClick(1702, 1033)
sleep(1)
pyautogui.press("w")
sleep(1)
pyautogui.press("t")
sleep(1)
pyautogui.typewrite("VirusUWU:3")
sleep(1)
pyautogui.press("enter")
sleep(1)
time.sleep(2)
pyautogui.leftClick(1678, 972)
pyautogui.leftClick(1678, 972)
sleep(2)
pyautogui.typewrite("Happyyyyy Birth day Hopeeeee!!!",random.uniform(0,0.5),None,True)
sleep(0.2)
pyautogui.press("enter")
pyautogui.typewrite("love youuu!! hope you have a great day im so happy that you are my freind.",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("your a great person i love spending time with you!",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("my little cute light i hope i can see you... less then half a year left but i will try to make it into a realty",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("remember if you hate your self i will all ways love you!",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("sorry i still cant make a",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("remember if you hate your self or feel bad i am here to hear you yap;3",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
pyautogui.typewrite("you are working really hard every day good job dont surender okay darling? ",random.uniform(0,0.5),None,True)
sleep(0.2)
press("enter")
sleep(0.2)
pyautogui.hotkey("ctrl","s")
sleep(0.1)
pyautogui.hotkey("alt", "f4")

